# Generated by Django 6.0 on 2026-01-02 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='classification',
            field=models.CharField(default='generic', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
    ]
