# Generated by Django 6.0 on 2026-01-03 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alert_case_event_classification_event_severity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='alerts_shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='events_shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
