# Generated by Django 6.0 on 2026-01-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alert_members_event_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineitem',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_items', to='core.alert'),
        ),
    ]
