# Generated by Django 6.0 on 2026-01-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_customer_alert_customer_event_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
