# Generated by Django 6.0 on 2026-01-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customercontact_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
