# Generated by Django 6.0 on 2026-01-05 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_customercontact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
