# Generated by Django 6.0 on 2026-01-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customercontact_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='iocs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
