# Generated by Django 6.0.1 on 2026-01-08 13:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_reporttemplate_reportinstance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentTimelineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, default='')),
                ('kind', models.CharField(blank=True, default='event', max_length=80)),
                ('source', models.CharField(blank=True, default='manual', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_timeline_items', to='core.event')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_timeline_items_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['occurred_at', 'created_at'],
                'indexes': [models.Index(fields=['case', 'occurred_at'], name='core_incide_case_id_16930e_idx')],
            },
        ),
    ]
