# Generated by Django 6.0.1 on 2026-01-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_incidenttimelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttimelineitem',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='info', max_length=20),
        ),
    ]
