# Generated by Django 6.0.1 on 2026-01-09 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alert_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0.0', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('base_url', models.CharField(blank=True, default='', max_length=500)),
                ('secret', models.CharField(blank=True, default='', max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddonAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_id', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=200)),
                ('scope', models.CharField(choices=[('case', 'Case'), ('ioc', 'IoC'), ('asset', 'Asset')], max_length=20)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('path', models.CharField(default='/', max_length=300)),
                ('timeout_ms', models.PositiveIntegerField(default=5000)),
                ('is_enabled', models.BooleanField(default=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.addon')),
            ],
            options={
                'unique_together': {('addon', 'action_id')},
            },
        ),
        migrations.CreateModel(
            name='ActionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=20)),
                ('target_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('result_message', models.TextField(blank=True, default='')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.addon')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.addonaction')),
            ],
        ),
    ]
