# Generated by Django 6.0.1 on 2026-01-10 09:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_addon_addonaction_actionrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_id', models.CharField(max_length=120)),
                ('target_type', models.CharField(choices=[('case', 'Case'), ('ioc', 'IoC'), ('asset', 'Asset')], db_index=True, max_length=20)),
                ('target_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('target_value', models.TextField(blank=True, db_index=True, default='')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, default='success', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.addon')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_results', to='core.event')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['case', 'target_type'], name='core_connec_case_id_61d50f_idx'), models.Index(fields=['case', 'target_type', 'target_key'], name='core_connec_case_id_7d0557_idx')],
            },
        ),
    ]
