# Generated by Django 6.0.1 on 2026-01-10 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_connectorresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorAllowlistDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=True)),
                ('connector_type', models.CharField(db_index=True, default='http', max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('encrypted_secret', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('target_type', models.CharField(choices=[('case', 'Case'), ('ioc', 'IoC'), ('asset', 'Asset')], db_index=True, max_length=20)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('base_url', models.CharField(default='', max_length=500)),
                ('path_template', models.CharField(default='', max_length=500)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('timeout_ms', models.IntegerField(default=8000)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='core.connectorinstance')),
            ],
            options={
                'indexes': [models.Index(fields=['instance', 'target_type'], name='core_connec_instanc_9f8de9_idx')],
                'unique_together': {('instance', 'name')},
            },
        ),
    ]
