# Generated by Django 6.0.1 on 2026-01-11 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_connectorallowlistdomain_connectorinstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorresult',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='core.connectorendpoint'),
        ),
        migrations.AddField(
            model_name='connectorresult',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.connectorinstance'),
        ),
        migrations.AlterField(
            model_name='connectorresult',
            name='addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='core.addon'),
        ),
    ]
