# Generated by Django 6.0.1 on 2026-01-11 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_connectorresult_endpoint_connectorresult_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionrun',
            name='connector_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_runs', to='core.connectorendpoint'),
        ),
        migrations.AddField(
            model_name='actionrun',
            name='connector_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_runs', to='core.connectorinstance'),
        ),
        migrations.AlterField(
            model_name='actionrun',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.addonaction'),
        ),
        migrations.AlterField(
            model_name='actionrun',
            name='addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.addon'),
        ),
    ]
