# Generated by Django 6.0.1 on 2026-01-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_actionrun_connector_endpoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectorendpoint',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='connectorresult',
            name='addon',
        ),
        migrations.AddField(
            model_name='connectorendpoint',
            name='headers_text',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
