# Generated by Django 6.0.1 on 2026-01-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_connectorendpoint_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='case_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
