# Generated by Django 6.0.1 on 2026-01-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_event_case_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNumberSequence',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
