# Generated by Django 6.0.1 on 2026-01-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_event_archived_at_caseretentionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='outcome',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='unknown', max_length=50),
        ),
    ]
