# Generated by Django 6.0.1 on 2026-01-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_event_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='unarchived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
