# Generated by Django 6.0.1 on 2026-01-28 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alert_owner_alertcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title_prefix', models.CharField(blank=True, default='', max_length=200)),
                ('base_description', models.TextField(blank=True, default='')),
                ('default_severity', models.CharField(blank=True, default='low', max_length=20)),
                ('default_classification', models.CharField(blank=True, default='unknown', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_templates_default_owner', to=settings.AUTH_USER_MODEL)),
                ('workbook_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_templates', to='core.workbooktemplate')),
            ],
        ),
    ]
