# Generated by Django 6.0.1 on 2026-01-31 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.RemoveConstraint(
            model_name='customeraccess',
            name='customeraccess_user_or_group_required',
        ),
        migrations.AddConstraint(
            model_name='customeraccess',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', True), _negated=True), name='customeraccess_user_or_group_required'),
        ),
        migrations.RemoveField(
            model_name='customeraccess',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
