# Generated by Django 6.0.1 on 2026-02-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_group_roles_remove_group_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='outcome',
            field=models.CharField(choices=[('true_positive_with_impact', 'TP with impact'), ('true_positive_without_impact', 'TP without impact'), ('false_positive_technical', 'FP technical'), ('false_positive', 'False positive'), ('legitimate', 'Legitimate'), ('not_applicable', 'Not applicable'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=50),
        ),
    ]
