# Generated by Django 6.0.1 on 2026-02-11 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alert_outcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseExchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], db_index=True, max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('other', 'Other')], db_index=True, default='email', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('sender', models.CharField(blank=True, default='', max_length=500)),
                ('to', models.JSONField(blank=True, default=list)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('references', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='core.event')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_exchanges_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['case', 'created_at'], name='core_caseex_case_id_973a79_idx'), models.Index(fields=['case', 'direction', 'created_at'], name='core_caseex_case_id_32e6f3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('message_id', ''), _negated=True), fields=('case', 'message_id'), name='uniq_case_message_id')],
            },
        ),
    ]
