# Generated by Django 6.0.1 on 2026-02-15 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_caseexchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseExchangeReplyQuickpart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case_exchange_reply_quickparts',
                'ordering': ['name', '-updated_at'],
            },
        ),
    ]
