# Generated by Django 6.0.1 on 2026-02-17 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_caseexchangereplyquickpart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_username', models.CharField(blank=True, default='', max_length=160)),
                ('action', models.CharField(max_length=180)),
                ('object_type', models.CharField(blank=True, default='', max_length=80)),
                ('object_id', models.CharField(blank=True, default='', max_length=80)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(blank=True, default='', max_length=12)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
