# Generated by Django 6.0.1 on 2026-02-21 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccess',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_access_rules', to='core.role'),
        ),
        migrations.AddConstraint(
            model_name='customeraccess',
            constraint=models.UniqueConstraint(fields=('customer', 'user', 'role'), name='uniq_customer_user_role'),
        ),
    ]
