# Generated by Django 6.0.1 on 2026-03-03 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customeraccess',
            name='customeraccess_user_or_group_required',
        ),
        migrations.RemoveConstraint(
            model_name='customeraccess',
            name='uniq_customer_user_role',
        ),
        migrations.AddConstraint(
            model_name='customeraccess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('role__isnull', True)), models.Q(('user__isnull', True), ('role__isnull', False)), _connector='OR'), name='customeraccess_exactly_one_of_user_or_role'),
        ),
        migrations.AddConstraint(
            model_name='customeraccess',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', True)), fields=('customer', 'user'), name='uniq_customer_user_access'),
        ),
        migrations.AddConstraint(
            model_name='customeraccess',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('customer', 'role'), name='uniq_customer_role_access'),
        ),
    ]
