# Generated by Django 6.0.3 on 2026-03-08 15:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customeraccess_customeraccess_user_or_group_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('context', models.TextField(blank=True, default='')),
                ('conclusion', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('to_do', 'To do'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='to_do', max_length=20)),
                ('verdict', models.CharField(choices=[('unknown', 'Unknown'), ('suspicious', 'Suspicious'), ('malicious', 'Malicious'), ('benign', 'Benign'), ('false_positive', 'False positive')], db_index=True, default='unknown', max_length=30)),
                ('investigation_started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('investigation_finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('search_timeframe_start', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('search_timeframe_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('iocs', models.JSONField(blank=True, default=list)),
                ('assets', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunts_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hunts', to='core.customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunts_owned', to=settings.AUTH_USER_MODEL)),
                ('reviewers', models.ManyToManyField(blank=True, related_name='hunts_reviewing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HuntJournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('note', 'Note'), ('query', 'Query'), ('finding', 'Finding'), ('pivot', 'Pivot'), ('connector_run', 'Connector run'), ('decision', 'Decision'), ('conclusion', 'Conclusion')], db_index=True, default='note', max_length=30)),
                ('text', models.TextField()),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('linked_ioc_value', models.CharField(blank=True, default='', max_length=500)),
                ('linked_asset_value', models.CharField(blank=True, default='', max_length=500)),
                ('linked_action_run_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunt_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.hunt')),
            ],
            options={
                'ordering': ['occurred_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HuntCaseLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('related', 'Related'), ('created_from_hunt', 'Created from hunt')], db_index=True, default='related', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_links', to='core.event')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunt_case_links_created', to=settings.AUTH_USER_MODEL)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_links', to='core.hunt')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('hunt', 'case'), name='uniq_hunt_case_link')],
            },
        ),
    ]
