# Generated by Django 6.0.3 on 2026-03-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hunt_huntjournalentry_huntcaselink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntjournalentry',
            name='entry_type',
            field=models.CharField(choices=[('note', 'Note'), ('query', 'Query'), ('finding', 'Finding'), ('pivot', 'Pivot'), ('escalation', 'Escalation'), ('connector_run', 'Connector run'), ('decision', 'Decision'), ('conclusion', 'Conclusion')], db_index=True, default='note', max_length=30),
        ),
    ]
