# Generated by Django 6.0.3 on 2026-03-12 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_huntjournalentry_entry_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('provider_kind', models.CharField(choices=[('litellm', 'LiteLLM'), ('openai_compatible', 'OpenAI Compatible'), ('other', 'Other')], max_length=40)),
                ('base_url', models.URLField(max_length=500)),
                ('api_key_secret_ref', models.CharField(max_length=255)),
                ('default_model', models.CharField(max_length=255)),
                ('timeout_seconds', models.PositiveIntegerField(default=60)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('entity_type', models.CharField(choices=[('ip', 'IP'), ('user', 'User'), ('host', 'Host'), ('domain', 'Domain'), ('hash', 'Hash'), ('generic', 'Generic')], max_length=32)),
                ('target_kind', models.CharField(choices=[('single', 'Single'), ('batch', 'Batch')], default='single', max_length=32)),
                ('remote_template_code', models.CharField(max_length=120)),
                ('allowed_variables_schema', models.JSONField(blank=True, default=dict)),
                ('max_time_range_hours', models.PositiveIntegerField(default=24)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=16)),
                ('is_enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SOARProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('provider_kind', models.CharField(choices=[('n8n', 'n8n'), ('splunk_soar', 'Splunk SOAR'), ('xsoar', 'XSOAR'), ('other', 'Other')], max_length=40)),
                ('base_url', models.URLField(max_length=500)),
                ('auth_secret_ref', models.CharField(max_length=255)),
                ('timeout_seconds', models.PositiveIntegerField(default=90)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatContextSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_type', models.CharField(blank=True, max_length=32)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('current_tab', models.CharField(blank=True, max_length=64)),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('context_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=120)),
                ('client_tab_id', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('prompt', models.TextField()),
                ('response_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_runs', to='core.aiprovider')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='core.chatcontextsnapshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatGeneratedDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('case_comment', 'Case comment'), ('alert_comment', 'Alert comment')], max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='core.chatrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('surface', models.CharField(choices=[('dedicated', 'Dedicated'), ('contextual', 'Contextual')], max_length=32)),
                ('page_type', models.CharField(blank=True, max_length=32)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('customer_id', models.CharField(blank=True, max_length=64)),
                ('client_tab_id', models.CharField(max_length=120)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatrun',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.chatsession'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatcontextsnapshot',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.chatsession'),
        ),
        migrations.CreateModel(
            name='ChatActionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.chatrun')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_runs', to='core.investigationtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='investigationtemplate',
            name='soar_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigation_templates', to='core.soarprovider'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'surface', 'updated_at'], name='core_chatse_user_id_e86e88_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['client_tab_id'], name='core_chatse_client__7ed360_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrun',
            index=models.Index(fields=['user', 'client_tab_id', 'status'], name='core_chatru_user_id_f8bff4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrun',
            index=models.Index(fields=['session', 'created_at'], name='core_chatru_session_9d4185_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatrun',
            unique_together={('session', 'request_id')},
        ),
    ]
