# Generated by Django 6.0.3 on 2026-03-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aiprovider_investigationtemplate_soarprovider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='api_key_secret_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
