# Generated by Django 6.0.3 on 2026-03-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_aiprovider_api_key_secret_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgenerateddraft',
            name='target_type',
            field=models.CharField(choices=[('case_comment', 'Case comment'), ('alert_comment', 'Alert comment'), ('hunt_note', 'Hunt note')], max_length=32),
        ),
    ]
