# Generated by Django 6.0.3 on 2026-03-15 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alertcomment_author_label_comment_author_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('file_path', models.CharField(max_length=1024)),
                ('file_size', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_backups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
