# Generated by Django 6.0.3 on 2026-03-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_instancebackup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatactionrun',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='chatactionrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatactionrun',
            name='raw_response_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatactionrun',
            name='remote_run_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chatactionrun',
            name='remote_status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='chatactionrun',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatactionrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationtemplate',
            name='execution_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='investigationtemplate',
            name='execution_mode',
            field=models.CharField(choices=[('provider_default', 'Provider default'), ('sync', 'Synchronous'), ('async', 'Asynchronous')], default='provider_default', max_length=20),
        ),
        migrations.AddField(
            model_name='investigationtemplate',
            name='input_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='investigationtemplate',
            name='output_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='investigationtemplate',
            name='status_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='soarprovider',
            name='auth_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='soarprovider',
            name='auth_config_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='soarprovider',
            name='auth_type',
            field=models.CharField(choices=[('none', 'None'), ('bearer', 'Bearer'), ('basic', 'Basic'), ('header', 'Header'), ('query', 'Query parameter')], default='bearer', max_length=20),
        ),
        migrations.AddField(
            model_name='soarprovider',
            name='request_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='soarprovider',
            name='response_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='soarprovider',
            name='status_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='soarprovider',
            name='verify_ssl',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatactionrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16),
        ),
        migrations.AlterField(
            model_name='investigationtemplate',
            name='entity_type',
            field=models.CharField(choices=[('ip', 'IP'), ('user', 'User'), ('host', 'Host'), ('domain', 'Domain'), ('hash', 'Hash'), ('url', 'URL'), ('email', 'Email'), ('generic', 'Generic')], max_length=32),
        ),
        migrations.AlterField(
            model_name='investigationtemplate',
            name='remote_template_code',
            field=models.CharField(help_text='Remote identifier of the target playbook, workflow, webhook or action.', max_length=255),
        ),
        migrations.AlterField(
            model_name='soarprovider',
            name='auth_secret_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='soarprovider',
            name='provider_kind',
            field=models.CharField(choices=[('generic_http', 'Generic HTTP'), ('n8n', 'n8n'), ('splunk_soar', 'Splunk SOAR'), ('xsoar', 'XSOAR'), ('other', 'Other')], db_index=True, default='generic_http', max_length=40),
        ),
        migrations.AddIndex(
            model_name='chatactionrun',
            index=models.Index(fields=['status', 'created_at'], name='core_chatac_status_1d4c08_idx'),
        ),
        migrations.AddIndex(
            model_name='chatactionrun',
            index=models.Index(fields=['template', 'created_at'], name='core_chatac_templat_326848_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationtemplate',
            index=models.Index(fields=['soar_provider', 'is_enabled'], name='core_invest_soar_pr_eb1ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationtemplate',
            index=models.Index(fields=['entity_type', 'target_kind'], name='core_invest_entity__ee8cfe_idx'),
        ),
    ]
