# Generated by Django 6.0.3 on 2026-03-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_chatactionrun_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationtemplate',
            name='selection_hint',
            field=models.TextField(blank=True),
        ),
    ]
