# Generated by Django 6.0.3 on 2026-03-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_alert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovider',
            name='default_system_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatrun',
            name='provider_execution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatrun',
            name='selected_command',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='chatrun',
            name='selected_template_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='investigationtemplate',
            name='ai_context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='investigationtemplate',
            name='chat_command',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='investigationtemplate',
            name='command_help',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='investigationtemplate',
            name='default_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='investigationtemplate',
            name='prompt_overrides_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
