# Generated by Django 6.0.3 on 2026-03-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aiprovider_default_system_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrun',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatrun',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatrun',
            name='worker_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
