# Generated by Django 6.0.3 on 2026-04-13 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_chatrun_cancel_requested_chatrun_cancel_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_followup_delay_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_followup_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_followup_quickpart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_auto_followup', to='core.caseexchangereplyquickpart'),
        ),
    ]
