# Generated by Django 6.0.3 on 2026-04-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_event_auto_followup_delay_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='auto_followup_delay_hours',
            new_name='auto_followup_delay_value',
        ),
        migrations.AddField(
            model_name='event',
            name='auto_followup_delay_unit',
            field=models.CharField(default='hour', max_length=16),
        ),
    ]
