# Generated by Django 6.0.4 on 2026-04-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_task_taskcaselink_taskcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='open', max_length=30),
        ),
    ]
