# Generated by Django 6.0.4 on 2026-05-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_event_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseTemplate',
        ),
    ]
