# Generated by Django 6.0.4 on 2026-05-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_casetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_followup_action',
            field=models.CharField(choices=[('save', 'Save only'), ('send', 'Send')], default='save', max_length=10),
        ),
    ]
