# Generated by Django 6.0.4 on 2026-05-01 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_event_auto_followup_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseExchangeFollowup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('delay_value', models.PositiveIntegerField(default=24)),
                ('delay_unit', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='hour', max_length=16)),
                ('action', models.CharField(choices=[('save', 'Save only'), ('send', 'Send')], default='save', max_length=10)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup_config', to='core.caseexchange')),
                ('quickpart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_followups', to='core.caseexchangereplyquickpart')),
            ],
            options={
                'indexes': [models.Index(fields=['enabled', 'updated_at'], name='core_caseex_enabled_4dcc7f_idx'), models.Index(fields=['action', 'enabled'], name='core_caseex_action_d5a1e2_idx')],
            },
        ),
    ]
