# Generated by Django 6.0.4 on 2026-05-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_caseexchangefollowup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sla_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
