# Generated by Django 6.0.4 on 2026-05-06 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_customer_sla_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseretentionsettings',
            name='exchange_send_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_exchange_send_settings', to='core.investigationtemplate'),
        ),
    ]
