# Generated by Django 6.0.4 on 2026-05-09 08:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_caseretentionsettings_exchange_send_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('scope', models.CharField(choices=[('alert', 'Alert'), ('case', 'Case'), ('hunt', 'Hunt')], db_index=True, max_length=20)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('run_once_per_target', models.BooleanField(default=True)),
                ('cooldown_seconds', models.PositiveIntegerField(default=0)),
                ('stop_on_first_action_error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(db_index=True, max_length=20)),
                ('target_id', models.CharField(db_index=True, max_length=80)),
                ('trigger', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('matched', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial_success', 'Partial success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='running', max_length=30)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('actions_results', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='core.automationrule')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['scope', 'is_enabled'], name='core_automa_scope_20460a_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['updated_at'], name='core_automa_updated_fe92ec_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['rule', 'target_id'], name='core_automa_rule_id_a7151c_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['scope', 'target_id', 'started_at'], name='core_automa_scope_e158c0_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['status', 'started_at'], name='core_automa_status_ccb9c2_idx'),
        ),
    ]
