# Generated by Django 6.0.4 on 2026-05-17 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_event_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='secret',
        ),
        migrations.AddField(
            model_name='addon',
            name='encrypted_secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='connectorendpoint',
            name='timeout_ms',
            field=models.PositiveIntegerField(default=8000),
        ),
        migrations.AddIndex(
            model_name='chatgenerateddraft',
            index=models.Index(fields=['target_type', 'target_id', 'is_posted'], name='core_chatge_target__196ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatgenerateddraft',
            index=models.Index(fields=['run', 'is_posted'], name='core_chatge_run_id_93157f_idx'),
        ),
        migrations.AddConstraint(
            model_name='actionrun',
            constraint=models.CheckConstraint(condition=models.Q(('connector_instance__isnull', False), ('connector_endpoint__isnull', False)), name='actionrun_requires_connector_instance_and_endpoint'),
        ),
        migrations.AddConstraint(
            model_name='aiprovider',
            constraint=models.CheckConstraint(condition=models.Q(('timeout_seconds__gte', 1), ('timeout_seconds__lte', 120)), name='ai_provider_timeout_seconds_range'),
        ),
        migrations.AddConstraint(
            model_name='connectorendpoint',
            constraint=models.CheckConstraint(condition=models.Q(('timeout_ms__gte', 1000), ('timeout_ms__lte', 60000)), name='connector_endpoint_timeout_ms_range'),
        ),
        migrations.AddConstraint(
            model_name='soarprovider',
            constraint=models.CheckConstraint(condition=models.Q(('timeout_seconds__gte', 1), ('timeout_seconds__lte', 120)), name='soar_provider_timeout_seconds_range'),
        ),
    ]
