# Generated by Django 6.0.5 on 2026-05-19 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_instanceproxysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceSplunkHecSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('endpoint', models.URLField(blank=True, default='', max_length=500)),
                ('token_secret_ref', models.TextField(blank=True, default='')),
                ('index', models.CharField(blank=True, default='', max_length=120)),
                ('source', models.CharField(blank=True, default='doko:audit', max_length=200)),
                ('sourcetype', models.CharField(blank=True, default='_json', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_splunk_hec_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
