# Generated by Django 6.0.5 on 2026-05-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_instancesplunkhecsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
