# Generated by Django 6.0.5 on 2026-05-22 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alert_sla_acknowledged_at_alert_sla_acknowledged_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='caseuserstate',
            name='core_caseus_event_i_82b898_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='incidenttimelineitem',
            index=models.Index(fields=['case', 'created_at'], name='core_incide_case_id_c950b0_idx'),
        ),
    ]
