# Generated by Django 6.0.5 on 2026-05-22 10:37

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_alert_created_at_alter_event_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['actions_results'], name='automationlog_actions_gin'),
        ),
        migrations.AddIndex(
            model_name='caseexchange',
            index=django.contrib.postgres.indexes.GinIndex(fields=['raw'], name='caseexchange_raw_gin'),
        ),
    ]
