# Generated by Django 6.0.5 on 2026-05-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_automationexecutionlog_automationlog_actions_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='status_before_merge',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('merged', 'Merged'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='', max_length=20),
        ),
    ]
