# Generated by Django 6.0.5 on 2026-05-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alert_status_before_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
