from django.urls import path

from .dashboard import dashboard, dashboard_preferences

from .search import unified_search

from .views import (
    me,
    me_update,
    EventListCreateView,
    EventRetrieveUpdateDestroyView,
    CaseMarkViewedView,
    TimelineItemListCreateForEventView,
    TimelineItemRetrieveUpdateDestroyView,
    CommentListCreateForEventView,
    CommentRetrieveUpdateDestroyView,
    AttachmentListCreateForEventView,
    AttachmentRetrieveDestroyView,
    AlertListCreateView,
    AlertListForEventView,
    AlertEscalateToCaseView,
    AlertLinkToCaseView,
    CaseListLiteView,
    UserLiteListView,
    AlertUnmergeView,
    CaseDeleteView,
    AlertDeleteView,
    AlertRetrieveUpdateDestroyView,
    SettingsSeverityListCreateView,
    SettingsSeverityRetrieveUpdateDestroyView,
    SettingsClassificationListCreateView,
    SettingsClassificationRetrieveUpdateDestroyView,
    SettingsCustomerListCreateView,
    SettingsCustomerRetrieveUpdateDestroyView,
    SettingsCustomerContactListCreateView,
    SettingsCustomerContactRetrieveUpdateDestroyView,
    WorkbookInstanceItemUpdateView,
    SettingsWorkbookTemplateListCreateView,
    SettingsWorkbookTemplateRetrieveUpdateDestroyView,
    SettingsWorkbookTemplateItemListCreateView,
    SettingsWorkbookTemplateItemRetrieveUpdateDestroyView,
    CaseWorkbookGetView,
    CaseWorkbookApplyTemplateView,
    SettingsReportTemplateListCreateView,
    SettingsReportTemplateRetrieveUpdateDestroyView,
    SettingsReportTemplatePreviewView,
    CaseReportGenerateView,
    CaseReportListView,
    CaseIncidentTimelineListCreateView,
    IncidentTimelineItemRetrieveUpdateDestroyView,
    CaseArchiveView,
    CaseUnarchiveView,
    AlertCommentListCreateForAlertView, 
    AlertCommentRetrieveUpdateDestroyView,
    ChangePasswordView, 
    UpdateAvatarView,
    CaseExchangeListCreateForCaseView,
    CaseExchangeRetrieveUpdateDestroyView,
    CaseExchangeReplyQuickpartViewSet,
    CaseExchangeFollowupBulkView,
    CaseExchangeSendView,
    HuntListCreateView,
    HuntRetrieveUpdateDestroyView,
    HuntDeleteView,
    HuntJournalEntryListCreateForHuntView,
    HuntJournalEntryRetrieveUpdateDestroyView,
    HuntCaseLinkListCreateForHuntView,
    HuntCaseLinkRetrieveDestroyView,
    HuntTimelineView,
    HuntArchiveView,
    HuntUnarchiveView,
    TaskListCreateView,
    TaskRetrieveUpdateDestroyView,
    TaskCommentListCreateView,
    TaskCommentRetrieveUpdateDestroyView,
    TaskCaseLinkListCreateView,
    TaskCaseLinkRetrieveDestroyView,
    TaskListForEventView,
)

from .views_settings import (
    SettingsUserListCreateView,
    SettingsUserRetrieveUpdateView,
    SettingsUserResetPasswordView,
    SettingsUserDisableView,
    SettingsRoleListCreateView,
    SettingsRoleRetrieveUpdateDestroyView,
    SettingsPermissionListView,
    CaseRetentionSettingsView,
    SettingsAuditLogListView,
    SettingsAuditLogDetailView,
    SettingsUserPasswordResetLinkView,
    SettingsRoleCustomerAccessView,
    AIProviderListCreateView,
    AIProviderDetailView,
    SOARProviderListCreateView,
    SOARProviderDetailView,
    InvestigationTemplateListCreateView,
    InvestigationTemplateDetailView,
    InstanceSettingsView,
    InstanceBackupCreateView,
    InstanceBackupDownloadView,
    InstanceBackupRestoreView,
    InstanceAuditExportView,
    InstanceSplunkHecSettingsView,
    InstanceSplunkHecTestView,
    SettingsUserApiTokenListCreateView,
    SettingsUserApiTokenRevokeView,
    AutomationRuleListCreateView,
    AutomationRuleDetailView,
    AutomationRuleMetadataView,
    InstanceProxySettingsView,
)


from .views_addons import (
    run_connector_action,
    list_connector_results,
    connector_instances,
    connector_instance_detail,
    connector_instance_add_endpoint,
    connector_endpoint_detail,
    connector_allowlist,
    connector_allowlist_detail,
)

from .views_auth import (
    ApiTokenListCreateView,
    ApiTokenRevokeView,
    CsrfCookieView,
    PasswordResetConfirmView,
    SessionLoginView,
    SessionLogoutView,
)

from .views_chat import (
    ChatSessionListCreateView,
    ChatSessionClearView,
    ChatRunCreateView,
    ChatRunDetailView,
    ChatGenerateDraftView,
    ChatPostDraftView,
    ChatSessionArchiveView,
    ChatActionListView,
    ChatRunCancelView,
)



urlpatterns = [
    path("auth/csrf/", CsrfCookieView.as_view(), name="auth-csrf"),
    path("auth/login/", SessionLoginView.as_view(), name="auth-login"),
    path("auth/logout/", SessionLogoutView.as_view(), name="auth-logout"),
    path("auth/api-tokens/", ApiTokenListCreateView.as_view(), name="auth-api-tokens"),
    path("auth/api-tokens/<str:token_key>/revoke/", ApiTokenRevokeView.as_view(), name="auth-api-token-revoke"),
    path("auth/password-reset/confirm/", PasswordResetConfirmView.as_view()),
    path("settings/users/<int:pk>/password-reset-link/", SettingsUserPasswordResetLinkView.as_view()),

    path("me/", me, name="me"),
    path("me/update/", me_update),
    path("me/change-password/", ChangePasswordView.as_view(), name="me-change-password"),
    path("me/avatar/", UpdateAvatarView.as_view(), name="me-avatar"),

    path("users-lite/", UserLiteListView.as_view(), name="users-lite"),

    path("events/", EventListCreateView.as_view(), name="event-list-create"),
    path("events/<uuid:pk>/", EventRetrieveUpdateDestroyView.as_view(), name="event-detail"),
    path("events/<uuid:event_id>/timeline-items/", TimelineItemListCreateForEventView.as_view(), name="timeline-list-create"),
    path("events/<uuid:event_id>/comments/", CommentListCreateForEventView.as_view(), name="comment-list-create"),
    path("events/<uuid:event_id>/attachments/", AttachmentListCreateForEventView.as_view(), name="attachment-list-create"),
    path("events/<uuid:pk>/delete/", CaseDeleteView.as_view(), name="case-delete"),
    path("events/<uuid:event_id>/alerts/", AlertListForEventView.as_view(), name="case-alerts"),
    path("events/<uuid:event_id>/tasks/", TaskListForEventView.as_view(), name="case-tasks"),
    path("events/<uuid:pk>/archive/", CaseArchiveView.as_view(), name="case-archive"),
    path("events/<uuid:pk>/unarchive/", CaseUnarchiveView.as_view(), name="case-unarchive"),
    path("cases/<uuid:case_id>/workbook/", CaseWorkbookGetView.as_view()),
    path("cases/<uuid:case_id>/workbook/apply/", CaseWorkbookApplyTemplateView.as_view()),
    path("cases/<uuid:case_id>/reports/", CaseReportListView.as_view()),
    path("cases/<uuid:case_id>/reports/generate/", CaseReportGenerateView.as_view()),
    path("cases/<uuid:case_id>/incident-timeline/", CaseIncidentTimelineListCreateView.as_view()),
    path("cases/<uuid:pk>/mark-viewed/", CaseMarkViewedView.as_view(), name="case-mark-viewed"),
    path("cases-lite/", CaseListLiteView.as_view(), name="case-list-lite"),
    path("comments/<uuid:pk>/", CommentRetrieveUpdateDestroyView.as_view(), name="comment-detail"),
    path("timeline-items/<uuid:pk>/", TimelineItemRetrieveUpdateDestroyView.as_view(), name="timeline-item-detail"),
    path("cases/<uuid:case_id>/exchanges/", CaseExchangeListCreateForCaseView.as_view()),
    path("exchanges/<uuid:pk>/", CaseExchangeRetrieveUpdateDestroyView.as_view()),
    path("cases/<uuid:case_id>/exchanges/send/", CaseExchangeSendView.as_view()),
    path("cases/<uuid:case_id>/exchanges/followups/", CaseExchangeFollowupBulkView.as_view()),

    path("attachments/<uuid:pk>/", AttachmentRetrieveDestroyView.as_view(), name="attachment-detail"),
    path("workbook-items/<int:pk>/", WorkbookInstanceItemUpdateView.as_view()),
    path("incident-timeline-items/<uuid:pk>/", IncidentTimelineItemRetrieveUpdateDestroyView.as_view()),

    path("alerts/", AlertListCreateView.as_view(), name="alert-list-create"),
    path("alerts/<uuid:pk>/", AlertRetrieveUpdateDestroyView.as_view(), name="alert-detail"),
    path("alerts/<uuid:pk>/escalate/", AlertEscalateToCaseView.as_view(), name="alert-escalate"),
    path("alerts/<uuid:pk>/link/", AlertLinkToCaseView.as_view(), name="alert-link"),
    path("alerts/<uuid:pk>/unmerge/", AlertUnmergeView.as_view(), name="alert-unmerge"),
    path("alerts/<uuid:pk>/delete/", AlertDeleteView.as_view(), name="alert-delete"),
    path("alerts/<uuid:alert_id>/comments/", AlertCommentListCreateForAlertView.as_view()),
    path("alert-comments/<uuid:pk>/", AlertCommentRetrieveUpdateDestroyView.as_view()),

    path("settings/users/", SettingsUserListCreateView.as_view(), name="settings-users"),
    path("settings/users/<int:pk>/", SettingsUserRetrieveUpdateView.as_view(), name="settings-user-detail"),
    path("settings/users/<int:pk>/edit/", SettingsUserRetrieveUpdateView.as_view(), name="settings-user-edit"),
    path("settings/users/<int:pk>/reset-password/", SettingsUserResetPasswordView.as_view(), name="settings-user-reset-password"),
    path("settings/users/<int:pk>/disable/", SettingsUserDisableView.as_view(), name="settings-user-disable"),
    path("settings/users/<int:pk>/api-tokens/", SettingsUserApiTokenListCreateView.as_view(), name="settings-user-api-tokens"),
    path("settings/users/<int:pk>/api-tokens/<str:token_key>/revoke/", SettingsUserApiTokenRevokeView.as_view(), name="settings-user-api-token-revoke"),

    path("settings/permissions/", SettingsPermissionListView.as_view(), name="settings-permissions"),

    path("settings/roles/", SettingsRoleListCreateView.as_view(), name="settings-roles"),
    path("settings/roles/<int:pk>/", SettingsRoleRetrieveUpdateDestroyView.as_view(), name="settings-role-detail"),
    path("settings/access/roles/<int:role_id>/customers/", SettingsRoleCustomerAccessView.as_view()),

    path("settings/data-models/severities/", SettingsSeverityListCreateView.as_view()),
    path("settings/data-models/severities/<int:pk>/", SettingsSeverityRetrieveUpdateDestroyView.as_view()),
    path("settings/data-models/classifications/", SettingsClassificationListCreateView.as_view()),
    path("settings/data-models/classifications/<int:pk>/", SettingsClassificationRetrieveUpdateDestroyView.as_view()),

    path("settings/customers/", SettingsCustomerListCreateView.as_view()),
    path("settings/customers/<uuid:pk>/", SettingsCustomerRetrieveUpdateDestroyView.as_view()),
    path("settings/customers/<uuid:customer_id>/contacts/", SettingsCustomerContactListCreateView.as_view()),
    path("settings/customer-contacts/<uuid:public_id>/", SettingsCustomerContactRetrieveUpdateDestroyView.as_view()),

    path("settings/workbook-templates/", SettingsWorkbookTemplateListCreateView.as_view()),
    path("settings/workbook-templates/<uuid:pk>/", SettingsWorkbookTemplateRetrieveUpdateDestroyView.as_view()),
    path("settings/workbook-templates/<uuid:template_id>/items/", SettingsWorkbookTemplateItemListCreateView.as_view()),
    path("settings/workbook-template-items/<uuid:pk>/", SettingsWorkbookTemplateItemRetrieveUpdateDestroyView.as_view()),

    path("settings/report-templates/", SettingsReportTemplateListCreateView.as_view()),
    path("settings/report-templates/<uuid:pk>/", SettingsReportTemplateRetrieveUpdateDestroyView.as_view()),
    path("settings/report-templates/preview/", SettingsReportTemplatePreviewView.as_view()),
    path("settings/case-retention/", CaseRetentionSettingsView.as_view()),
    path("settings/case-exchange-reply-quickparts/", CaseExchangeReplyQuickpartViewSet.as_view({"get": "list", "post": "create"}), name="case-exchange-reply-quickparts",),
    path("settings/case-exchange-reply-quickparts/<uuid:pk>/", CaseExchangeReplyQuickpartViewSet.as_view({"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy", }), name="case-exchange-reply-quickparts-detail",),

    path("settings/automation-rules/", AutomationRuleListCreateView.as_view()),
    path("settings/automation-rules/metadata/", AutomationRuleMetadataView.as_view()),
    path("settings/automation-rules/<uuid:pk>/", AutomationRuleDetailView.as_view()),

    path("connectors/run/", run_connector_action),
    path("connectors/results/", list_connector_results),
    path("connectors/instances/", connector_instances),
    path("connectors/instances/<str:instance_id>/", connector_instance_detail),
    path("connectors/instances/<str:instance_id>/endpoints/", connector_instance_add_endpoint),
    path("connectors/endpoints/<str:endpoint_id>/", connector_endpoint_detail),
    path("connectors/allowlist/", connector_allowlist),
    path("connectors/allowlist/<str:domain_id>/", connector_allowlist_detail),

    path("settings/audit/", SettingsAuditLogListView.as_view(), name="settings-audit"),
    path("settings/audit/<uuid:pk>/", SettingsAuditLogDetailView.as_view(), name="settings-audit-detail"),

    path("hunts/", HuntListCreateView.as_view(), name="hunt-list-create"),
    path("hunts/<uuid:pk>/", HuntRetrieveUpdateDestroyView.as_view(), name="hunt-detail"),
    path("hunts/<uuid:pk>/delete/", HuntDeleteView.as_view(), name="hunt-delete"),
    path("hunts/<uuid:hunt_id>/journal/", HuntJournalEntryListCreateForHuntView.as_view(), name="hunt-journal-list-create"),
    path("hunt-journal/<uuid:pk>/", HuntJournalEntryRetrieveUpdateDestroyView.as_view(), name="hunt-journal-detail"),
    path("hunts/<uuid:hunt_id>/case-links/", HuntCaseLinkListCreateForHuntView.as_view(), name="hunt-case-links"),
    path("hunt-case-links/<uuid:pk>/", HuntCaseLinkRetrieveDestroyView.as_view(), name="hunt-case-link-detail"),
    path("hunts/<uuid:hunt_id>/timeline/", HuntTimelineView.as_view(), name="hunt-timeline"),
    path("hunts/<uuid:pk>/archive/", HuntArchiveView.as_view(), name="hunt-archive"),
    path("hunts/<uuid:pk>/unarchive/", HuntUnarchiveView.as_view(), name="hunt-unarchive"),

    path("settings/ai/providers", AIProviderListCreateView.as_view()),
    path("settings/ai/providers/<uuid:pk>", AIProviderDetailView.as_view()),
    path("settings/soar/providers", SOARProviderListCreateView.as_view()),
    path("settings/soar/providers/<uuid:pk>", SOARProviderDetailView.as_view()),
    path("settings/ai/investigation-templates", InvestigationTemplateListCreateView.as_view()),
    path("settings/ai/investigation-templates/<uuid:pk>", InvestigationTemplateDetailView.as_view()),

    path("chat/sessions", ChatSessionListCreateView.as_view()),
    path("chat/sessions/<uuid:session_id>/runs", ChatRunCreateView.as_view()),
    path("chat/runs/<uuid:run_id>", ChatRunDetailView.as_view()),
    path("chat/runs/<uuid:run_id>/drafts", ChatGenerateDraftView.as_view()),
    path("chat/drafts/<uuid:draft_id>/post", ChatPostDraftView.as_view()),
    path("chat/sessions/<uuid:session_id>/clear", ChatSessionClearView.as_view()),
    path("chat/sessions/<uuid:session_id>/archive/", ChatSessionArchiveView.as_view()),
    path("chat/actions", ChatActionListView.as_view()),
    path("chat/runs/<uuid:run_id>/cancel", ChatRunCancelView.as_view()),

    path("settings/instance/", InstanceSettingsView.as_view()),
    path("settings/instance/proxy/", InstanceProxySettingsView.as_view()),
    path("settings/instance/splunk-hec/", InstanceSplunkHecSettingsView.as_view()),
    path("settings/instance/splunk-hec/test/", InstanceSplunkHecTestView.as_view()),
    path("settings/instance/audit-export/", InstanceAuditExportView.as_view()),
    path("settings/instance/backup/", InstanceBackupCreateView.as_view()),
    path("settings/instance/backup/<uuid:backup_id>/download/", InstanceBackupDownloadView.as_view()),
    path("settings/instance/backup/restore/", InstanceBackupRestoreView.as_view()),

    path("tasks/", TaskListCreateView.as_view(), name="task-list-create"),
    path("tasks/<uuid:pk>/", TaskRetrieveUpdateDestroyView.as_view(), name="task-detail"),
    path("tasks/<uuid:task_id>/comments/", TaskCommentListCreateView.as_view(), name="task-comment-list-create"),
    path("task-comments/<uuid:pk>/", TaskCommentRetrieveUpdateDestroyView.as_view(), name="task-comment-detail"),
    path("tasks/<uuid:task_id>/cases/", TaskCaseLinkListCreateView.as_view(), name="task-case-link-list-create"),
    path("task-case-links/<uuid:pk>/", TaskCaseLinkRetrieveDestroyView.as_view(), name="task-case-link-detail"),

    path("search/", unified_search),

    path("dashboard/", dashboard),
    path("dashboard/preferences/", dashboard_preferences),

]